"""Regenerate numbers_pooled.tex and the Pooled* blocks of
runs/MF2_wildreceipt_softmax.json from the (corrected, leakage-free)
LOCKED CORD/SROIE cells in MF2_wildreceipt_softmax.py plus the already
computed WildReceipt block in the run JSON.

This is a pure-stdlib decontamination helper: MF2's model inference
(LayoutLMv3 / WildReceipt download) is NOT re-run; only the pooling
arithmetic and tex emission are recomputed so the pooled row reflects
the canonical CORD test+validation (n=200) evaluation.
"""
import json
import math
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SRC = ROOT / "scripts/smoke/MF2_wildreceipt_softmax.py"
OUT_JSON = ROOT / "runs/MF2_wildreceipt_softmax.json"
OUT_TEX = ROOT / "paper/asyu/numbers_pooled.tex"


def load_locked():
    ns = {}
    text = SRC.read_text()
    # Extract the LOCKED = { ... } literal and eval it safely.
    start = text.index("LOCKED = {")
    depth = 0
    i = text.index("{", start)
    j = i
    while j < len(text):
        if text[j] == "{":
            depth += 1
        elif text[j] == "}":
            depth -= 1
            if depth == 0:
                j += 1
                break
        j += 1
    literal = text[i:j]
    return eval(literal, {"__builtins__": {}}, ns)


def wilson_ci(k, n, z=1.96):
    if n == 0:
        return (0.0, 0.0)
    p = k / n
    z2 = z * z
    center = (p + z2 / (2 * n)) / (1 + z2 / n)
    inner = p * (1 - p) / n + z2 / (4 * n * n)
    margin = (z / (1 + z2 / n)) * (inner ** 0.5)
    return (max(0.0, center - margin), min(1.0, center + margin))


def main():
    locked = load_locked()
    data = json.loads(OUT_JSON.read_text())
    wr = data["WildReceipt"]

    keys = ("n", "sigma_acc", "sigma_corr", "smax_acc", "smax_corr",
            "int_acc", "int_corr", "sigonly_acc", "sigonly_corr",
            "smonly_acc", "smonly_corr", "b_mcnemar", "c_mcnemar")

    def pool(key):
        return locked["CORD"][key] + locked["SROIE"][key] + wr[key]

    pooled = {k: pool(k) for k in keys}

    def wci(k, n):
        lo, hi = wilson_ci(k, n)
        return (round(lo, 3), round(hi, 3))

    pooled_ci = {
        "sigma":   wci(pooled["sigma_corr"],   pooled["sigma_acc"]),
        "smax":    wci(pooled["smax_corr"],    pooled["smax_acc"]),
        "int":     wci(pooled["int_corr"],     pooled["int_acc"]),
        "sigonly": wci(pooled["sigonly_corr"], pooled["sigonly_acc"]),
        "smonly":  wci(pooled["smonly_corr"],  pooled["smonly_acc"]),
    }

    bp, cp = pooled["b_mcnemar"], pooled["c_mcnemar"]
    chi2_pooled = ((abs(bp - cp) - 1) ** 2) / max(1, bp + cp)
    try:
        from scipy.stats import chi2 as chi2_dist
        p_pooled = float(chi2_dist.sf(chi2_pooled, 1))
    except Exception:
        p_pooled = math.erfc((chi2_pooled / 2) ** 0.5)

    data["Pooled"] = pooled
    data["Pooled_CIs"] = pooled_ci
    data["Pooled_McNemar"] = {
        "b": bp, "c": cp,
        "chi2": round(chi2_pooled, 4),
        "p_value": round(p_pooled, 4),
    }
    OUT_JSON.write_text(json.dumps(data, indent=2))

    tex_lines = [
        "% Auto-generated by scripts/smoke/regen_pooled_from_locked.py",
        "% (leakage-free: CORD = test+validation n=200)",
        f"\\renewcommand{{\\poolN}}{{{pooled['n']}}}",
        f"\\renewcommand{{\\poolSigA}}{{{pooled['sigma_acc']}}}",
        f"\\renewcommand{{\\poolSigC}}{{{pooled['sigma_corr']}}}",
        f"\\renewcommand{{\\poolIntA}}{{{pooled['int_acc']}}}",
        f"\\renewcommand{{\\poolIntC}}{{{pooled['int_corr']}}}",
        f"\\renewcommand{{\\poolMcB}}{{{bp}}}",
        f"\\renewcommand{{\\poolMcC}}{{{cp}}}",
        f"\\renewcommand{{\\poolMcChi}}{{{chi2_pooled:.3f}}}",
        f"\\renewcommand{{\\poolMcP}}{{{p_pooled:.3f}}}",
        f"\\renewcommand{{\\wrN}}{{{wr['n']}}}",
        f"\\renewcommand{{\\wrIntA}}{{{wr['int_acc']}}}",
        f"\\renewcommand{{\\wrIntC}}{{{wr['int_corr']}}}",
        "",
    ]
    OUT_TEX.write_text("\n".join(tex_lines))
    print(json.dumps({"Pooled": pooled, "Pooled_CIs": pooled_ci,
                       "Pooled_McNemar": data["Pooled_McNemar"]}, indent=2))


if __name__ == "__main__":
    main()
