#!/usr/bin/env python3
"""Number provenance -- which numbers were measured, and which were typed?

Catches the failure in 04-WORKED-EXAMPLES Example 3: a number that entered the
paper as an estimate, was rendered, cited, and carried into two decks, and was
never measured by anything.

An unmeasured number is indistinguishable from a measured one at the point of
reading, and MORE plausible on average, because it was generated by the same
intuition that judges it. The only defence is provenance.

The rule: every number in the paper resolves to exactly one generated file,
which resolves to exactly one run artifact.

  provenance          every macro used in the paper has a generator
  literals            numeric literals typed directly into prose
  orphans             generated macros nothing uses (a dropped result)

Exit 0 clean, 1 on findings, 2 if nothing was found to check.

Usage:
  number_provenance.py <main.tex> [--generated numbers_*.tex ...]
                                  [--runs ../../runs]
"""
import glob
import os
import re
import sys

# Numeric literals that are structural rather than results.
BENIGN = re.compile(r"""
    ^(?:0|1|2|3|4|5|6|7|8|9|10|100|1000|      # small counts
       0\.0|1\.0|0\.5|                        # trivial
       95|99|05|01)$                          # confidence levels
""", re.X)

# Contexts where a numeric literal is not a result.
# \newcommand and \renewcommand lines are the safe DEFAULTS of the results
# bridge, not typed results -- flagging them buries the real findings, and a
# check that cries wolf gets switched off.
SKIP_CONTEXT = re.compile(
    r'\\(?:new|renew)command|'
    r'\\(?:label|ref|cite|includegraphics|documentclass|usepackage|'
    r'setlength|definecolor|scale|width|height|node|draw|fill|'
    r'begin|end|hspace|vspace|rule|column|multirow|multicolumn|'
    r'arraystretch|emergencystretch|exhyphenpenalty|fbox\w*|'
    r'newif|if\w+|pdfstringdef\w*|DeclareRobust\w*|foreach|circle|'
    r'rectangle|minimum|InputIfFileExists|usetikzlibrary|hypersetup)')


def strip_comments(text):
    return re.sub(r'(?<!\\)%.*', '', text)


def macros_used(src):
    """Macros the document uses, excluding definitions and LaTeX built-ins."""
    defined_here = set(re.findall(r'\\(?:new|renew)command\{?\\([A-Za-z]+)', src))
    used = {}
    for m in re.finditer(r'\\([A-Za-z]+)(?![A-Za-z])', src):
        name = m.group(1)
        used.setdefault(name, 0)
        used[name] += 1
    return used, defined_here


def generated_macros(paths):
    """Macros a numbers_*.tex file actually assigns, and the file that does it."""
    gen = {}
    for p in paths:
        try:
            t = strip_comments(open(p, encoding='utf8').read())
        except OSError:
            continue
        for name in re.findall(r'\\(?:new|renew)command\{\\([A-Za-z]+)\}', t):
            gen.setdefault(name, []).append(os.path.basename(p))
    return gen


def generator_scripts(paths):
    """The 'Auto-generated by ...' provenance line, when the file carries one."""
    prov = {}
    for p in paths:
        try:
            head = open(p, encoding='utf8').read(400)
        except OSError:
            continue
        m = re.search(r'(?:Auto-)?[Gg]enerated by\s+(\S+)', head)
        prov[os.path.basename(p)] = m.group(1) if m else None
    return prov


def literals_in_prose(src):
    """Numeric literals typed into body text rather than rendered from a macro."""
    hits = []
    # only look outside math-heavy structural commands
    for n, line in enumerate(src.split('\n'), 1):
        if SKIP_CONTEXT.search(line):
            continue
        for m in re.finditer(r'(?<![\w.])(\d+\.\d+)(?![\w.])', line):
            val = m.group(1)
            if BENIGN.match(val):
                continue
            hits.append((n, val, line.strip()[:88]))
    return hits


def main(argv):
    if len(argv) < 2:
        print(__doc__)
        return 2

    tex = argv[1]
    gen_paths = []
    if '--generated' in argv:
        i = argv.index('--generated') + 1
        while i < len(argv) and not argv[i].startswith('--'):
            gen_paths.extend(glob.glob(argv[i]))
            i += 1
    if not gen_paths:
        gen_paths = glob.glob(os.path.join(os.path.dirname(tex) or '.',
                                           'numbers_*.tex'))
        gen_paths += glob.glob(os.path.join(os.path.dirname(tex) or '.',
                                            '*_curve.tex'))

    src = strip_comments(open(tex, encoding='utf8').read())
    used, defined_here = macros_used(src)
    gen = generated_macros(gen_paths)
    prov = generator_scripts(gen_paths)

    if not gen:
        print(f"{tex}: NO GENERATED NUMBER FILES FOUND -- either this paper has "
              f"no results bridge, or the paths are wrong. Check did not run.")
        return 2

    rc = 0
    print(f"{tex}")
    print(f"  generated files: {len(gen_paths)}   result macros: {len(gen)}")

    # 1. every result macro the paper uses must have a generator
    unbacked = sorted(n for n in gen
                      if n in defined_here and n not in gen and used.get(n, 0) > 1)
    # macros defined in main.tex with a numeric default and NO generator file
    numeric_default = re.findall(
        r'\\newcommand\{\\([A-Za-z]+)\}\{([-0-9][^}]*)\}', src)
    typed = sorted({name for name, _ in numeric_default
                    if name not in gen and used.get(name, 0) > 1})
    if typed:
        rc = 1
        print("  UNBACKED result macros -- a numeric value with no generator:")
        for name in typed:
            print(f"    \\{name}  (used {used[name] - 1}x, defined only in "
                  f"{os.path.basename(tex)})")
    else:
        print("  unbacked result macros: NONE")

    # 2. provenance of each generator file
    missing_prov = [f for f, s in prov.items() if s is None]
    if missing_prov:
        print("  generated files with no 'Auto-generated by' provenance line:")
        for f in sorted(missing_prov):
            print(f"    {f}")
        print("      (not a failure, but you cannot answer 'which run made this'"
              " from the file alone)")

    # 3. orphaned results -- generated but never used.
    #    The dangerous subset is an orphan whose VALUE appears in the paper as a
    #    literal: the number is typed where a generated macro was available, so
    #    the two can drift. That is how a pooled McNemar row came to print
    #    183/188 while its per-corpus rows summed to 185/188.
    orphans = sorted(n for n in gen if used.get(n, 0) <= 1)
    shadowed = []
    for n in orphans:
        try:
            val = re.search(r'\\(?:new|renew)command\{\\' + n + r'\}\{([^}]*)\}',
                            open(gen[n][0] if os.path.exists(gen[n][0])
                                 else os.path.join(os.path.dirname(tex) or '.',
                                                   gen[n][0]),
                                 encoding='utf8').read()).group(1)
        except (OSError, AttributeError):
            continue
        if not re.fullmatch(r'-?\d+(?:\.\d+)?', val):
            continue
        body = re.sub(r'\\(?:new|renew)command\{\\[A-Za-z]+\}\{[^}]*\}', '', src)
        if re.search(r'(?<![\w.])' + re.escape(val) + r'(?![\w.])', body):
            shadowed.append((n, val, gen[n][0]))
    if shadowed:
        rc = 1
        print("  TYPED WHERE A MACRO EXISTS -- the value is a literal in the "
              "paper while its generated macro goes unused:")
        for n, val, f in shadowed:
            print(f"    {val:<10} \\{n}  <- {f}")
        print("      These two copies can drift. Route the literal through the "
              "macro.")
    other = [n for n in orphans if n not in {s[0] for s in shadowed}]
    if other:
        print(f"  orphaned results, value not in the paper ({len(other)}) -- "
              f"computed and then dropped; confirm intentional:")
        print("    " + ", ".join("\\" + n for n in other[:18])
              + (" ..." if len(other) > 18 else ""))

    # 4. numeric literals typed into prose
    lits = literals_in_prose(src)
    if lits:
        print(f"  NUMERIC LITERALS in prose ({len(lits)}) -- each should be a "
              f"macro, or be justified:")
        for n, val, ctx in lits[:25]:
            print(f"    line {n}: {val}   {ctx}")
        if len(lits) > 25:
            print(f"    ... and {len(lits) - 25} more")
        rc = 1
    else:
        print("  numeric literals in prose: NONE")

    return rc


if __name__ == '__main__':
    sys.exit(main(sys.argv))
